// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEYjvP6pfmeqQ6iJMyOkAEY1sejSN47m8',
    appId: '1:646938337554:android:030f5cb0249fa5d8fc13cb',
    messagingSenderId: '646938337554',
    projectId: 'finansasistaniapp',
    storageBucket: 'finansasistaniapp.firebasestorage.app',
  );

  // ios/Runner/GoogleService-Info.plist ile birebir aynı olmalı.
  // Plist yeniden indirilirse bu blok da güncellenmeli.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSx0zaMJj-6tbKO_CKYYqaCXnyiCGnu8k',
    appId: '1:646938337554:ios:c9c378faf4827cc4fc13cb',
    messagingSenderId: '646938337554',
    projectId: 'finansasistaniapp',
    storageBucket: 'finansasistaniapp.firebasestorage.app',
    iosBundleId: 'com.emrec.muhasebe',
    iosClientId:
        '646938337554-iom3uueoll8h7i6hrrlrvv8e8etvguvl.apps.googleusercontent.com',
  );
}
